import { ArrowUpRight, CheckCircle2, ChevronRight, Mail, MapPin, Phone, RadioTower, Wifi, Wrench } from "lucide-react";
import { BackToTop } from "@/components/back-to-top";

const roles = [
  { period:"APR 2024 — PRESENT", company:"Integer Telecom Services", title:"Senior RAN Integration Engineer / L2", location:"Hyderabad, India", detail:"Leading Ericsson LTE/5G RAN integration and advanced troubleshooting for AT&T East and West markets, including Nokia-to-Ericsson network modernization.", points:["Integrated and commissioned 380+ Ericsson LTE/5G sites across DRAN and CRAN architectures using ENM, AMOS/Moshell, Node Integration Wizard and CME.","Perform end-to-end eNodeB/gNodeB integration, software commissioning and upgrades, carrier and sector additions, network script execution and configuration validation.","Provide live tower-crew support for Nokia-to-Ericsson swap cutovers, radio and antenna replacements, cabling corrections and service bring-up.","Isolate and resolve RSSI, VSWR, PIM, fiber-loss, CPRI/eCPRI, RET, radio, baseband, transport and synchronization faults.","Commission and troubleshoot Ericsson BB5216/6630/6648/6651/6672, RRU 4415/4426/4449/8843 and AIR 32/6419/6449 equipment.","Create and validate IDL, ERAN and RI-link connectivity; coordinate WDM MUX unlocks and transport restoration with NOC and MNRC teams.","Execute PSAP/Auto-PSAP, E911, FCT, PLA and call testing, resolving integration blockers before site handover.","Own MOP and CIQ execution, change-window activities, rollback readiness, incident documentation and technical coordination through service restoration."] },
  { period:"JUL 2021 — APR 2024", company:"MasTec QuadGen Wireless Solutions", title:"RAN Integration Engineer", location:"Visakhapatnam, India", detail:"Delivered remote integration and troubleshooting support for Ericsson LTE/5G deployments on the AT&T network.", points:["Performed eNodeB/gNodeB commissioning, network script execution, NSB and carrier additions, software upgrades and alarm clearance.","Integrated Ericsson basebands, RRUs and AIR units; validated hardware connectivity, sector configuration, RETs and radio operational status.","Troubleshot RAN, transport, S1/X2/NG connectivity, configuration and synchronization issues during site integration and cutover windows.","Created and verified neighbor relations and supported PSAP, emergency-call and functional call testing with field and NOC teams.","Analyzed node logs and alarms through ENM, OSS-RC and AMOS/CLI, driving technical issues to resolution and site handover."] },
  { period:"JUN 2019 — JUL 2020", company:"Progility Technologies Pvt. Ltd.", title:"Graduate Engineer Trainee", location:"Hyderabad, India", detail:"Built an early foundation in telecom infrastructure deployment, commissioning, equipment testing and field documentation.", points:[] },
];
const skills = [
  ["RAN integration","Ericsson LTE, VoLTE, 5G NR NSA, eNB/gNB commissioning, DRAN/CRAN"],
  ["Troubleshooting","Alarm triage, RCA, RSSI, VSWR, PIM, fiber loss, service restoration"],
  ["Tools & scripting","ENM, AMOS, Moshell, CME, Node Integration Wizard, XML/MML, Python"],
  ["Performance","RRC, ERAB, HO, PRB, RSRP, RSRQ, SINR, throughput and KPI acceptance"],
  ["Transport & testing","ERAN, IDL, eCPRI, RI-links, PSAP, E911, FCT, PLA and call testing"],
  ["Operations","Remedy incidents, MOP/CIQ execution, change control, crew and NOC coordination"],
];
const toolGroups = [
  ["Ericsson RAN", "ENM · OSS-RC · AMOS · Moshell · Node Integration Wizard · CME · IOP · Mobatch"],
  ["Scripting", "CLI · XML · MML · SCF · Python · Bash/Shell · Ansible"],
  ["Troubleshooting", "Wireshark · BMC Remedy · ServiceNow · GOTO/MNRC · Granite"],
  ["Analysis", "Advanced Excel · Power BI · Log analysis · Configuration validation"],
];
const projects = [
  { tag:"NETWORK MODERNIZATION", title:"AT&T Nokia-to-Ericsson LTE/5G Swap", copy:"Supported live-network swap cutovers from pre-checks through service restoration, coordinating tower crews while resolving radio, antenna, RET, fiber and external-alarm issues.", proof:"Swap execution · Crew support · Fault isolation" },
  { tag:"RAN DELIVERY", title:"Ericsson LTE/5G Integration", copy:"Integrated and commissioned 380+ Ericsson sites across AT&T markets, covering baseband and radio bring-up, scripting, transport connectivity, software upgrades and functional acceptance.", proof:"380+ sites · DRAN/CRAN · 4G/5G" },
  { tag:"TECHNICAL ENABLEMENT", title:"6673 DRAN Sidehaul Knowledge Share", copy:"Created and delivered a technical presentation on Ericsson 6673 commissioning, cabling and sidehaul architecture to help engineers approach integrations with greater clarity.", proof:"Knowledge sharing · Team enablement" },
];
const strengths = [
  ["Quick learner", "I absorb unfamiliar tools, procedures and network designs quickly, then apply them carefully in live delivery."],
  ["Continuous growth", "I actively expand my knowledge in vRAN, Open RAN, 5G SA, automation and emerging telecom technologies."],
  ["Smart working", "I look for repeatable methods, scripts and better workflows that reduce manual effort without compromising quality."],
  ["Ownership mindset", "I stay engaged from the first alarm or integration blocker until the issue is clearly resolved and documented."],
];

export default function Home(){return <main>
  <header className="site-header"><a className="brand" href="#top"><span>RS</span> Ram Sai Pavan Kumar Reddi <small>(Ram)</small></a><nav><a href="#experience">Experience</a><a href="#expertise">Skills</a><a href="#projects">Projects</a><a href="#mindset">Mindset</a></nav><a className="contact-pill" href="mailto:ramsaipavankumarreddi@gmail.com">Let&apos;s connect <ArrowUpRight size={16}/></a></header>
  <section className="hero" id="top"><div className="signal-field" aria-hidden="true"><i/><i/><i/><i/></div><div className="hero-copy"><p className="eyebrow"><span/> Available for new opportunities</p><h1>Building reliable<br/><em>networks at scale.</em></h1><p className="intro">Senior RAN Integration &amp; Troubleshooting Engineer with 6+ years of experience delivering Ericsson LTE and 5G networks for AT&amp;T.</p><div className="hero-actions"><a className="primary-button" href="#experience">Explore my work <ChevronRight size={17}/></a><a className="text-link" href="mailto:ramsaipavankumarreddi@gmail.com">Email me <ArrowUpRight size={15}/></a></div></div><div className="hero-proof"><div className="proof-card featured"><RadioTower size={22}/><strong>380+</strong><span>LTE &amp; 5G sites integrated</span></div><div className="proof-card"><strong>6+</strong><span>Years in RAN engineering</span></div><div className="proof-card"><strong>4G / 5G</strong><span>Ericsson network expertise</span></div></div></section>
  <section className="ticker"><span>ERICSSON RAN</span><b>◆</b><span>LTE / VoLTE</span><b>◆</b><span>5G NR NSA</span><b>◆</b><span>NETWORK MODERNIZATION</span><b>◆</b><span>ROOT CAUSE ANALYSIS</span></section>
  <section className="section intro-grid"><div><p className="section-number">01 / PROFILE</p><h2>I turn complex network issues into stable customer experiences.</h2></div><div className="profile-copy"><p>My work sits where planning meets live-network reality: integrating new capacity, guiding field teams through tough faults, and validating every change before it reaches the customer.</p><p>Across Ericsson and AT&amp;T programs, I combine disciplined troubleshooting with clear cross-team coordination—taking ownership from the first alarm through KPI acceptance and service restoration.</p><div className="location"><MapPin size={17}/> Visakhapatnam, India · Open to remote opportunities</div></div></section>
  <section className="section" id="experience"><div className="section-head"><p className="section-number">02 / EXPERIENCE</p><h2>Experience that keeps<br/>critical networks moving.</h2></div><div className="timeline">{roles.map((r,i)=><article className="role" key={r.company}><div className="role-meta"><span>{r.period}</span><small>{r.location}</small></div><div className="role-body"><p className="company">{r.company}</p><h3>{r.title}</h3><p className="role-detail">{r.detail}</p>{r.points.length>0&&<ul>{r.points.map(p=><li key={p}><CheckCircle2 size={16}/>{p}</li>)}</ul>}</div><div className="role-index">0{i+1}</div></article>)}</div></section>
  <section className="expertise" id="expertise"><div className="section-head light"><p className="section-number">03 / TECHNICAL EXPERTISE</p><h2>From integration script<br/>to customer experience.</h2></div><div className="skill-grid">{skills.map(([t,c],i)=><article key={t}><span>0{i+1}</span>{i===0?<Wifi size={25}/>:i===1?<Wrench size={25}/>:null}<h3>{t}</h3><p>{c}</p></article>)}</div><div className="knowledge-note"><span>EXPANDING KNOWLEDGE</span> vRAN · Open RAN · 5G SA &amp; Core fundamentals · Automation with Python, Bash &amp; Ansible</div></section>
  <section className="section tools-section"><div className="section-head"><p className="section-number">04 / TOOLS</p><h2>A practical toolkit for<br/>live-network delivery.</h2></div><div className="tool-stack">{toolGroups.map(([t,c])=><div key={t}><strong>{t}</strong><p>{c}</p></div>)}</div></section>
  <section className="projects-section" id="projects"><div className="section-head light"><p className="section-number">05 / KEY PROJECTS</p><h2>Selected work with<br/>real network impact.</h2></div><div className="project-grid">{projects.map((p,i)=><article key={p.title}><span className="project-no">0{i+1}</span><p className="project-tag">{p.tag}</p><h3>{p.title}</h3><p>{p.copy}</p><strong>{p.proof}</strong></article>)}</div></section>
  <section className="mindset-section" id="mindset"><div className="mindset-lead"><p className="section-number">06 / HOW I WORK</p><h2>Learn fast.<br/><em>Think clearly.</em><br/>Deliver reliably.</h2><p>I thrive on learning new technologies and turning that learning into practical value. Curiosity helps me ask better questions; disciplined execution helps me produce dependable results.</p></div><div className="strength-list">{strengths.map(([t,c],i)=><article key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{c}</p></div></article>)}</div></section>
  <section className="section education" id="education"><div><p className="section-number">07 / EDUCATION</p><h2>Engineering foundation.<br/>Continuous learning.</h2></div><div className="credential-list"><div><span>2015 — 2019</span><h3>B.Tech, Electronics &amp; Communication Engineering</h3><p>Viswanadha Institute of Technology and Management · JNTU Kakinada</p></div><div><span>CERTIFICATION</span><h3>4G &amp; 5G Protocol Testing</h3><p>Completed professional certification</p></div><div><span>CERTIFICATION</span><h3>Python Developer</h3><p>Udemy</p></div></div></section>
  <footer><div><p className="eyebrow"><span/> Ready for the next challenge</p><h2>Let&apos;s build networks<br/>that perform.</h2></div><div className="footer-links"><a href="mailto:ramsaipavankumarreddi@gmail.com"><Mail size={18}/> ramsaipavankumarreddi@gmail.com</a><a href="tel:+919494706041"><Phone size={18}/> +91 94947 06041</a><a href="https://linkedin.com/in/ram-sai-reddi-49baa3159/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={16}/></a></div><p className="copyright">© 2026 Ram Sai Reddi · Senior RAN Integration &amp; Troubleshooting Engineer</p></footer>
  <BackToTop />
</main>}
